### ISSUE TITLE
KeyError: 'MCM'

### ISSUE THREAD

**Issue by togekiss0603** [lianqi1008/MCM#5]
Sampler_train = <torch.utils.data.distributed.DistributedSampler object at 0x7bf6fd98aa50>
Traceback (most recent call last):
  File "/home/qzy/MCM/main_compress.py", line 244, in <module>
    main(args)
  File "/home/qzy/MCM/main_compress.py", line 193, in main
    net = models[args.model](visual_tokens=args.vis_num)
          ~~~~~~^^^^^^^^^^^^
KeyError: 'MCM'

Given the fact that "compressai" in this project is a littel strange, I use the "pip install compressai" to carry on the following. But It seems that I haven't seen 'MCM' in labels.
In "main_compress.py": from compressai.zoo import models
args.model = 'MCM'
    net = models[args.model](visual_tokens=args.vis_num)

**Comment by lianqi1008** [comment]
This issue may be due to compressai not being installed locally. Please try installing it by following the instructions in the Dependencies and Installation section of the README.
